Repository amittri1025/Whatsapp-Link-Gen, pull requests merged in 2023-10, with the labels that each got.

#23 FIXED BACK-TO-TOP BUTTON
  index.html
  style.css
Labels: hacktoberfest

#33 Updated - Go to top button
  index.html
  style.css
Labels: hacktoberfest

#35 fix: dark mode persists in LocalStorage
  app.js
Labels: hacktoberfest, hacktoberfest2023

#37 Updated the README.md file and improved the documentation
  README.md
  images/logo.png
  images/webpage_ss.png
Labels: hacktoberfest, hacktoberfest2023, hacktober-accepted

#48 added contact page (fixed previous issues)
  contact.css
  contact.html
  index.html
Labels: hacktoberfest-accepted

#53 Scrollbar
  style.css
Labels: hacktoberfest-accepted

#54 Fix overflow and remove unneeded links
  contact.css
  contact.html
Labels: hacktoberfest-accepted

#56 Toggle button text changes to Light when Dark Mode applied and vice versa
  app.js
Labels: hacktoberfest-accepted

#57 Dropdown width adjusts with change in option selected
  app.js
  index.html
  style.css
Labels: hacktoberfest-accepted

#60 Styling the scroll bar
  style.css
Labels: hacktoberfest-accepted

#64 FIX Responsiveness Issue in the hero section
  index.html
Labels: hacktoberfest-accepted

#69 [FIX]Clicking on Logo doesn't navigate to homescreen
  contact.html
  index.html
Labels: hacktoberfest-accepted

#73 [FEAT] Replace Dark Mode Button with Icon Button Toggle
  app.js
  index.html
Labels: hacktoberfest-accepted

#93 Favicon added
  images/favicon.png
  index.html
  style.css
Labels: hacktoberfest-accepted

#91 Fix generate link button width
  style.css
Labels: hacktoberfest-accepted

#105 Order country code alphabetically
  index.html
Labels: hacktoberfest-accepted

#108 Added a logo
  images/WhiSave-removebg-preview.png
Labels: hacktoberfest-accepted
